import arduinoUnoImage from '../../assets/arduino_uno.jpg';
import buzzerImage from '../../assets/buzzer.jpg';
import hcSr04Image from '../../assets/hcsr04.jpg';
import ldrImage from '../../assets/ldr.jpg';
import ledImage from '../../assets/led.jpg';
import motorImage from '../../assets/motor.jpg';
import mpu6050Image from '../../assets/mpu6050.jpg';
import ponteHImage from '../../assets/ponteH.jpg';
import pushButtonImage from '../../assets/botãopush.jpg';
import resistorImage from '../../assets/resistor.jpg';
import esp32DevKitImage from '../../assets/esp32_devkit_v1.jpg';
import esp32PinoutImage from '../../assets/ESP32-DevKit-V1_Pinos.png';
import esp32ConnectionImage from '../../assets/ESP-DevKit-V1_ComoLigar.png';
import type {
  ComponentCatalogItem,
  ComponentCategory,
  ComponentCategoryId,
  ComponentId,
} from './types';

export const COMPONENT_CATEGORIES: readonly ComponentCategory[] = [
  { id: 'microcontrollers', label: 'Microcontroladores', description: 'Placas que executam o programa.', accent: 'blue' },
  { id: 'sensors', label: 'Sensores', description: 'Entradas que percebem o ambiente.', accent: 'violet' },
  { id: 'actuators', label: 'Atuadores', description: 'Saídas que transformam sinais em ação.', accent: 'orange' },
  { id: 'modules', label: 'Módulos', description: 'Circuitos prontos para funções específicas.', accent: 'green' },
  { id: 'motors', label: 'Motores', description: 'Movimento elétrico para projetos.', accent: 'pink' },
  { id: 'electronic-components', label: 'Componentes eletrônicos', description: 'Peças fundamentais do circuito.', accent: 'slate' },
  { id: 'power', label: 'Alimentação', description: 'Fontes e distribuição de energia.', accent: 'orange' },
  { id: 'communication', label: 'Comunicação', description: 'Conexões entre dispositivos.', accent: 'blue' },
  { id: 'tools', label: 'Ferramentas', description: 'Itens de montagem e medição.', accent: 'slate' },
];

export const COMPONENT_CATALOG: readonly ComponentCatalogItem[] = [
  {
    id: 'esp32-devkit-v1',
    name: 'ESP32 DevKit V1',
    categoryId: 'microcontrollers',
    illustration: 'board',
    summary: 'Uma placa com Wi‑Fi e Bluetooth que dá cérebro e voz sem fio aos seus projetos.',
    purpose: 'Executa programas, lê sensores e controla luzes, sons e motores (sempre usando um driver). É a placa certa quando o projeto precisa conversar com um celular, outra placa ou a internet.',
    student: {
      whatIs: 'É o cérebro do projeto: ele recebe informações, toma decisões e manda sinais para as outras peças.',
      usefulFor: 'Criar robôs, alarmes, sensores conectados, controles pelo celular e projetos que usam Wi‑Fi ou Bluetooth.',
      howToConnect: 'Comece por USB. Nos circuitos, una os GNDs e use GPIO 21 (SDA) e 22 (SCL) para I²C.',
      attention: 'Pense em 3,3 V: nenhum GPIO do ESP32 pode receber sinal de 5 V.',
      bloquinExample: 'Faça um sensor perceber algo e mandar um aviso sem fio.',
    },
    howItWorks: 'No meio da placa existe um chip chamado ESP32. Ele lê seu programa muitas vezes por segundo e transforma cada instrução em pequenos sinais elétricos de 0 V ou 3,3 V nos GPIOs. Esses sinais podem escutar um botão, medir um sensor ou dar uma ordem a um LED e a um driver de motor. A antena desenhada no topo também é parte do chip: ela transforma dados em ondas de rádio para usar Wi‑Fi e Bluetooth, sem acrescentar outro módulo.',
    codeLogic: 'No início, os blocos dizem ao ESP32 quais GPIOs vão ouvir (entradas) e quais vão agir (saídas). Depois, o programa repete: lê o sensor, compara o resultado e escolhe uma ação. Para um LED, escrever LIGADO coloca 3,3 V no pino; para ler um botão, o ESP32 observa se o pino está em nível alto ou baixo. Em um projeto sem fio, primeiro você prepara a conexão e depois troca mensagens usando o rádio que já está ligado.',
    parts: [
      { label: 'Módulo ESP-WROOM-32', description: 'A caixa metálica no centro. Lá dentro mora o ESP32, a memória do programa e a parte de rádio.' },
      { label: 'Antena Wi‑Fi/Bluetooth', description: 'O desenho em zigue-zague no alto do módulo. Deixe essa região livre, longe de metal e de fios enrolados.' },
      { label: 'Porta micro-USB', description: 'É o caminho mais simples: conecta ao computador para enviar o programa e também alimenta a placa.' },
      { label: 'Botão EN (reset)', description: 'Reinicia a placa e começa o programa de novo. É útil quando ela parece ter travado.' },
      { label: 'Botão BOOT', description: 'Ajuda a entrar no modo de gravação se o computador não conseguir enviar o programa automaticamente.' },
      { label: 'GPIOs', description: 'As duas fileiras de pinos. GPIO é uma portinha programável: alguns leem, outros leem e escrevem.' },
      { label: 'VIN, 3V3 e GND', description: 'São os pinos de energia. GND é o caminho de volta e precisa ser comum a todas as peças do circuito.' },
      { label: 'Regulador de tensão', description: 'Perto da USB, ele adapta a energia recebida para os 3,3 V usados pelo chip.' },
    ],
    tags: ['Wi‑Fi', 'Bluetooth', '3,3 V', 'projetos conectados'],
    specifications: [
      'Lógica de 3,3 V: HIGH significa perto de 3,3 V, não 5 V.',
      'Wi‑Fi e Bluetooth já vêm dentro do módulo.',
      'Pode usar entradas/saídas digitais, PWM, I²C, SPI, serial, touch e leitura analógica.',
      'Leitura analógica de até 12 bits: no Bloquin, de 0 a 4095.',
      'GPIO 34, 35, 36 (VP) e 39 (VN) servem apenas para entrada.',
      'Para um sensor analógico enquanto o Wi‑Fi está ligado, prefira GPIO 32, 33, 34, 35, 36 ou 39 (ADC1).',
    ],
    pins: [
      { label: 'USB, VIN e 3V3', role: 'power', description: 'Use USB no começo. VIN recebe 5 V regulados; 3V3 é para energia 3,3 V já regulada ou módulos leves de 3,3 V.' },
      { label: 'GND', role: 'ground', description: 'É o “chão” do circuito. Una o GND do ESP32 ao GND de cada sensor, driver e fonte externa.' },
      { label: 'GPIO 4, 13, 14, 16–19, 21–23, 25–27, 32 e 33', role: 'digital', description: 'Boas primeiras escolhas para sinais digitais. Escolha um livre e dê a ele um nome no seu projeto.' },
      { label: 'GPIO 21 / 22 (I²C)', role: 'i2c', description: 'São os padrões: GPIO 21 é SDA (dados) e GPIO 22 é SCL (ritmo). Vários sensores I²C podem compartilhar os dois fios.' },
      { label: 'GPIO 32, 33, 34, 35, 36 e 39 (ADC1)', role: 'analog', description: 'Leem valores analógicos de sensores. São a melhor família para leituras quando você também usa Wi‑Fi.' },
      { label: 'GPIO 34, 35, 36 e 39', role: 'analog', description: 'Somente entrada: ótimos para sensores, mas não acendem LED, não fazem PWM e não têm pull-up/pull-down interno.' },
      { label: 'GPIO 16 / 17 (Serial2)', role: 'signal', description: 'RX2 e TX2 podem conversar com outro módulo serial. São uma opção prática quando USB está ocupando a serial principal.' },
      { label: 'GPIO 18, 19, 23 e 5 (SPI)', role: 'digital', description: 'Pinos comuns para módulos SPI: SCK, MISO, MOSI e CS. O GPIO 5 exige atenção durante a inicialização.' },
      { label: 'GPIO 0, 2, 5, 12 e 15', role: 'digital', description: 'Pinos de boot: a placa olha para eles ao ligar. Use apenas quando souber que o módulo conectado não mudará seu nível no início.' },
      { label: 'GPIO 6 a 11', role: 'digital', description: 'São usados internamente pela memória flash do ESP32. Não use em projetos; geralmente eles nem aparecem nos conectores.' },
      { label: 'EN', role: 'signal', description: 'Não é GPIO. Levar EN para nível baixo reinicia/desliga o chip; o botão EN faz isso por um instante.' },
    ],
    connections: [
      { title: '1. Alimente de um jeito só', description: 'Para programar e testar, conecte apenas o USB. Sem USB, use VIN com 5 V regulados ou 3V3 com 3,3 V regulados — nunca uma bateria desconhecida direto em um GPIO.' },
      { title: '2. Faça o GND comum', description: 'Conecte o GND do ESP32 ao GND do sensor ou driver. Sem esse caminho de volta, os sinais não têm uma referência e o circuito fica imprevisível.' },
      { title: '3. Sensor I²C', description: 'No MPU6050: SDA → GPIO 21, SCL → GPIO 22, GND → GND e VCC conforme a tensão indicada no módulo. Um mesmo par SDA/SCL pode atender mais de um sensor.' },
      { title: '4. LED ou buzzer', description: 'Use um GPIO de saída seguro, como 18. Para LED: GPIO → resistor → perna longa do LED; perna curta → GND. Para buzzer, confira se ele aceita 3,3 V.' },
      { title: '5. Motor', description: 'GPIOs controlam apenas a entrada de um driver, como L298N. O motor usa sua própria fonte e todos os GNDs precisam estar unidos.' },
    ],
    cautions: [
      'Nunca ligue uma saída de 5 V diretamente a um GPIO: use divisor de tensão ou conversor de nível quando necessário.',
      'GPIO 34, 35, 36 e 39 são apenas entrada e precisam de resistor externo se o sensor deixar o sinal “solto”.',
      'Evite GPIO 0, 2, 5, 12 e 15 no primeiro projeto: fios nesses pinos podem impedir o ESP32 de iniciar ou receber um programa.',
      'GPIO 1 (TX0) e 3 (RX0) são a conversa USB/serial do computador. Usá-los pode misturar mensagens e atrapalhar a gravação.',
      'Nunca alimente um motor, servo ou fita de LEDs pelo GPIO ou pelo 3V3 do ESP32. Use fonte adequada e driver quando preciso.',
      'A imagem com baterias mostra onde entram energia e GND; antes de usar, confirme que sua fonte é regulada e tem a tensão certa para VIN ou 3V3.',
    ],
    relatedBlocks: [
      { blockType: 'configurar_pino', label: 'Configurar pino', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'escrever_pino', label: 'Colocar pino em estado', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'espnow_iniciar_wifi', label: 'Preparar comunicação sem fio', toolboxCategory: 'ESP-NOW' },
    ],
    relatedComponentIds: ['mpu6050', 'l298n', 'hc-sr04'],
    media: [
      { kind: 'image', role: 'main', src: esp32DevKitImage, alt: 'Placa ESP32 DevKit V1', caption: 'Compare a placa da imagem com a que está na sua mesa.' },
      { kind: 'image', role: 'pinout', src: esp32PinoutImage, alt: 'Diagrama dos pinos da ESP32 DevKit V1, incluindo GPIO, alimentação e funções especiais', caption: 'O número grande é a posição; procure o nome GPIO antes de conectar um fio.' },
      { kind: 'image', role: 'connection', src: esp32ConnectionImage, alt: 'Exemplo de alimentação da ESP32 DevKit V1 por USB ou por uma fonte externa ligada a VIN e GND', caption: 'USB é a opção mais simples. Em fonte externa, confirme a tensão regulada antes de ligar.' },
    ],
  },
  {
    id: 'arduino-uno',
    name: 'Arduino Uno',
    categoryId: 'microcontrollers',
    illustration: 'board',
    summary: 'Placa de 5 V simples e popular para os primeiros projetos de eletrônica.',
    purpose: 'Executa o programa e oferece pinos digitais, PWM e entradas analógicas para montar protótipos com sensores e atuadores.',
    student: {
      whatIs: 'Uma placa para começar a programar circuitos.',
      usefulFor: 'Ler sensores e mandar sinais para luzes e sons.',
      howToConnect: 'Use 5V e GND; escolha um pino para cada peça.',
      attention: 'Motor não liga direto na placa.',
      bloquinExample: 'Faça um LED piscar.',
    },
    howItWorks: 'O coração do Uno é o chip ATmega328P: ele guarda o seu programa em uma memória interna e o executa sem parar, como uma receita lida em looping. A cada passo, ele confere os pinos configurados como entrada e muda os pinos de saída entre 0 V e 5 V — é essa troca rápida de tensão que acende LEDs, toca sons e lê sensores.',
    codeLogic: 'O código do Arduino sempre tem uma parte que roda uma vez, para configurar os pinos, e depois entra em um laço que se repete sem parar. Um bloco de ler pino digital pergunta ao chip se há 0 V ou 5 V naquele fio; um bloco de escrever pino faz o oposto, obrigando o pino a virar 0 V ou 5 V. Já os blocos de PWM ligam e desligam o pino muitas vezes por segundo, tão rápido que o LED ou motor parece receber um valor intermediário de força.',
    parts: [
      { label: 'Chip ATmega328P', description: 'O componente preto retangular com várias perninhas. É o microcontrolador que executa o seu código.' },
      { label: 'Porta USB tipo B', description: 'Onde o cabo do computador entra para carregar o programa e alimentar a placa.' },
      { label: 'Botão de reset', description: 'Reinicia o programa do começo sem precisar tirar a energia da placa.' },
      { label: 'Fileiras de pinos digitais e analógicos', description: 'Os furos numerados nas bordas (0–13 digitais, A0–A5 analógicos) onde tudo é conectado.' },
      { label: 'LED embutido (pino 13)', description: 'Uma luzinha já ligada na placa, útil para testar se o código está rodando.' },
      { label: 'Conector de alimentação', description: 'Entrada redonda para ligar uma fonte externa quando o projeto não usa USB.' },
    ],
    tags: ['Arduino', 'ATmega328P', '5 V', 'iniciante'],
    specifications: ['Lógica de 5 V', '14 pinos digitais, sendo 6 com PWM', '6 entradas analógicas (A0–A5)', 'Leitura analógica de 0–1023 no Bloquin'],
    pins: [
      { label: '5V', role: 'power', description: 'Alimentação de módulos de 5 V de baixo consumo.' },
      { label: 'GND', role: 'ground', description: 'Terra comum do circuito.' },
      { label: 'D3, D5, D6, D9, D10, D11', role: 'digital', description: 'Pinos com PWM para brilho de LED e velocidade de motor via driver.' },
      { label: 'A0–A5', role: 'analog', description: 'Entradas para sensores analógicos, como LDR.' },
      { label: 'A4 / A5', role: 'i2c', description: 'SDA e SCL para módulos I²C.' },
    ],
    connections: [
      { title: 'LED', description: 'Use um pino digital, resistor em série e GND.' },
      { title: 'Sensor analógico', description: 'Ligue a saída do divisor do sensor em uma entrada A0–A5.' },
    ],
    cautions: ['Não alimente motor, fita de LEDs ou servo diretamente pelo pino 5V da placa.', 'D0 e D1 são usados pela comunicação USB/serial; prefira outros pinos em projetos comuns.'],
    relatedBlocks: [
      { blockType: 'configurar_pino', label: 'Configurar pino', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'ler_pino_analogico', label: 'Ler sensor analógico', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'escrever_pino_pwm', label: 'Força do pino (PWM)', toolboxCategory: 'Entradas e Saídas' },
    ],
    relatedComponentIds: ['led-5mm', 'ldr', 'hc-sr04'],
    media: [{ kind: 'image', role: 'main', src: arduinoUnoImage, alt: 'Placa Arduino Uno' }],
  },
  {
    id: 'led-5mm',
    name: 'LED',
    categoryId: 'electronic-components',
    illustration: 'led',
    summary: 'Diodo emissor de luz para indicar estados, criar sinais visuais e testar saídas.',
    purpose: 'Acende quando a corrente passa no sentido correto. É uma forma segura e visível de aprender a controlar uma saída digital.',
    student: {
      whatIs: 'Uma luz pequena para mostrar o que o projeto está fazendo.',
      usefulFor: 'Dar avisos, sinais e cores ao projeto.',
      howToConnect: 'Pino → resistor → perna longa; perna curta → GND.',
      attention: 'Sempre use resistor.',
      bloquinExample: 'Acenda a luz quando apertar um botão.',
    },
    howItWorks: 'Um LED é feito de dois pedacinhos de material semicondutor colados um no outro. Quando a corrente elétrica entra pelo lado certo (ânodo) e sai pelo outro (cátodo), os elétrons "pulam" de um pedaço para o outro e, ao pousar, soltam a energia extra em forma de luz — quase sem esquentar, diferente de uma lâmpada antiga.',
    codeLogic: 'O bloco de colocar pino em estado manda o pino para 5 V (ou 3,3 V no ESP32), o que empurra corrente pelo resistor e pelo LED, acendendo-o; mandar o mesmo pino para 0 V apaga a luz. Já o bloco de PWM liga e desliga o pino centenas de vezes por segundo: quanto mais tempo ligado em cada ciclo, mais brilhante o LED parece, mesmo sem mudar a voltagem.',
    parts: [
      { label: 'Cúpula (lente)', description: 'A parte de plástico colorido e arredondada no topo. Espalha a luz que sai de dentro.' },
      { label: 'Perna longa — Ânodo (+)', description: 'A perna mais comprida. É por onde a corrente entra; liga no resistor e no pino de saída.' },
      { label: 'Perna curta — Cátodo (−)', description: 'A perna mais curta, do lado achatado da base. É por onde a corrente sai; liga ao GND.' },
      { label: 'Lado achatado da base', description: 'Uma marca reta na borda perto da perna curta — ajuda a identificar o cátodo mesmo se as pernas forem cortadas.' },
    ],
    tags: ['luz', 'saída', 'polaridade', '220 Ω'],
    specifications: ['Possui polaridade', 'Use resistor em série', 'Corrente típica: cerca de 10–20 mA', 'Cores diferentes têm quedas de tensão diferentes'],
    pins: [
      { label: 'Ânodo (+)', role: 'signal', description: 'Perna normalmente mais longa; vai ao resistor e ao pino de saída.' },
      { label: 'Cátodo (−)', role: 'ground', description: 'Lado chato do encapsulamento; vai ao GND.' },
    ],
    connections: [
      { title: 'LED com Arduino', description: 'Pino digital → resistor de 220 Ω a 330 Ω → ânodo; cátodo → GND.' },
      { title: 'LED com ESP32', description: 'GPIO → resistor de 220 Ω a 330 Ω → ânodo; cátodo → GND.' },
    ],
    cautions: ['Nunca ligue um LED diretamente entre um pino e GND: use resistor.', 'Se não acender, desligue a alimentação e confira a polaridade.'],
    relatedBlocks: [
      { blockType: 'configurar_pino', label: 'Configurar pino como saída', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'escrever_pino', label: 'Ligar/desligar pino', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'escrever_pino_pwm', label: 'Controlar brilho (PWM)', toolboxCategory: 'Entradas e Saídas' },
    ],
    relatedComponentIds: ['resistor', 'arduino-uno', 'esp32-devkit-v1'],
    media: [{ kind: 'image', role: 'main', src: ledImage, alt: 'LED vermelho de 5 mm' }],
  },
  {
    id: 'resistor',
    name: 'Resistor',
    categoryId: 'electronic-components',
    illustration: 'resistor',
    summary: 'Componente que limita corrente e ajuda a dividir tensão em um circuito.',
    purpose: 'Protege LEDs e entradas, define estados lógicos com pull-up/pull-down e forma divisores de tensão com sensores como o LDR.',
    student: {
      whatIs: 'A peça que diminui a força da corrente.',
      usefulFor: 'Proteger LED e ajudar sensores a medir.',
      howToConnect: 'Com LED, coloque-o no caminho da corrente.',
      attention: 'Ele não tem lado certo.',
      bloquinExample: 'Monte uma luz segura com resistor de 220 Ω.',
    },
    howItWorks: 'Por dentro, um resistor tem uma fina camada de carbono que dificulta a passagem dos elétrons — parecido com um cano mais estreito dificultando a passagem de água. Quanto maior o valor em ohms, mais "apertado" fica esse caminho e menos corrente passa por ele; é assim que ele protege o LED de receber corrente demais.',
    codeLogic: 'O resistor não aparece diretamente em nenhum bloco — ele é só fiação —, mas está por trás de tudo: quando você usa ler pino analógico em um sensor como o LDR, é a dupla resistor + sensor que transforma luz em uma tensão, e essa tensão vira um número de 0 a 1023 (Arduino) ou 0 a 4095 (ESP32) para o bloco usar.',
    parts: [
      { label: 'Corpo cerâmico', description: 'O cilindro bege no meio. Guarda o material que resiste à passagem da corrente.' },
      { label: 'Faixas coloridas', description: 'As listras pintadas no corpo. Cada cor é um número — juntas, formam o valor em ohms (Ω).' },
      { label: 'Terminais', description: 'Os dois fios metálicos nas pontas. Não têm lado certo: o resistor funciona igual dos dois jeitos.' },
    ],
    tags: ['220 Ω', '10 kΩ', 'sem polaridade', 'corrente'],
    specifications: ['Não possui polaridade', 'Valor em ohms (Ω)', '220 Ω a 330 Ω é comum com LEDs', '10 kΩ é comum em botões e divisores'],
    pins: [
      { label: 'Terminal 1', role: 'signal', description: 'Pode ser ligado em qualquer lado: não há polaridade.' },
      { label: 'Terminal 2', role: 'signal', description: 'Pode ser ligado em qualquer lado: não há polaridade.' },
    ],
    connections: [
      { title: 'Limitar LED', description: 'Coloque o resistor em série entre o pino e o LED.' },
      { title: 'Divisor com LDR', description: 'Use LDR e resistor de 10 kΩ entre alimentação e GND; leia o ponto central em uma entrada analógica.' },
    ],
    cautions: ['Escolha valor e potência adequados; um resistor muito pequeno pode aquecer.', 'As faixas de cor indicam o valor. Confirme com multímetro quando houver dúvida.'],
    relatedBlocks: [
      { blockType: 'ler_pino_analogico', label: 'Ler sensor analógico', toolboxCategory: 'Entradas e Saídas', description: 'Usado quando o resistor forma um divisor com LDR.' },
    ],
    relatedComponentIds: ['led-5mm', 'ldr', 'push-button'],
    media: [{ kind: 'image', role: 'main', src: resistorImage, alt: 'Resistor eletrônico' }],
  },
  {
    id: 'push-button',
    name: 'Botão tátil',
    categoryId: 'electronic-components',
    illustration: 'button',
    summary: 'Interruptor momentâneo para enviar uma entrada digital ao programa.',
    purpose: 'Permite que a pessoa controle o projeto. Quando pressionado, fecha o circuito entre seus dois lados elétricos.',
    student: {
      whatIs: 'Um interruptor que você aperta.',
      usefulFor: 'Avisar o programa que alguém fez uma ação.',
      howToConnect: 'Um lado vai ao pino; o outro, ao GND.',
      attention: 'Confira a posição no protoboard antes de ligar.',
      bloquinExample: 'Aperte para ligar um LED.',
    },
    howItWorks: 'Dentro da capa de metal existe uma pequena cúpula elástica. Quando você aperta, ela se achata e toca dois contatos por baixo, fechando o circuito como se fosse uma pontezinha; quando solta, a cúpula volta ao formato original e separa os contatos de novo.',
    codeLogic: 'Com configurar pino como entrada com pull-up, o pino fica em 5 V (ou 3,3 V) sempre que o botão está solto. Ao apertar, o botão liga o pino direto ao GND, e o bloco de ler pino digital passa a devolver 0 (LOW) — por isso, no Bloquin, "botão apertado" costuma significar "ler falso/0", o que confunde no início mas fica automático depois de um projeto ou dois.',
    parts: [
      { label: 'Capa metálica', description: 'A tampinha prateada no topo. Protege a cúpula interna e é onde seu dedo aperta.' },
      { label: 'Cúpula interna', description: 'Uma peça elástica escondida dentro do botão. Dobra ao ser apertada e liga os contatos.' },
      { label: 'Pernas do lado A', description: 'As duas pernas de um lado, já ligadas entre si por dentro.' },
      { label: 'Pernas do lado B', description: 'As duas pernas do outro lado — o outro contato, também ligado por dentro.' },
    ],
    tags: ['entrada', 'digital', 'pull-up', 'interruptor'],
    specifications: ['Normalmente aberto (NA)', 'Não possui polaridade', 'As duas pernas de cada lado já são conectadas internamente', 'Pode usar resistor externo ou INPUT_PULLUP'],
    pins: [
      { label: 'Lado A', role: 'signal', description: 'As duas pernas deste lado são o mesmo contato.' },
      { label: 'Lado B', role: 'ground', description: 'As duas pernas deste lado são o outro contato.' },
    ],
    connections: [
      { title: 'Com INPUT_PULLUP', description: 'Um lado no pino digital e o outro no GND. No código, pressionado costuma ler 0 (LOW).' },
      { title: 'Com pull-down externo', description: 'Use resistor de 10 kΩ ao GND e o botão ao VCC para a leitura ficar HIGH quando pressionado.' },
    ],
    cautions: ['Confira a orientação no protoboard: girar o botão em 90° pode unir contatos incorretamente.', 'Não deixe uma entrada digital sem pull-up ou pull-down.'],
    relatedBlocks: [
      { blockType: 'configurar_pino', label: 'Configurar pino como entrada', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'ler_pino_digital', label: 'Ler pino digital', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'se_entao', label: 'Se… então', toolboxCategory: 'Lógica' },
    ],
    relatedComponentIds: ['resistor', 'led-5mm', 'passive-buzzer'],
    media: [{ kind: 'image', role: 'main', src: pushButtonImage, alt: 'Botão tátil' }],
  },
  {
    id: 'passive-buzzer',
    name: 'Buzzer passivo',
    categoryId: 'actuators',
    illustration: 'buzzer',
    summary: 'Emite tons ao receber uma frequência em um pino de saída.',
    purpose: 'Cria avisos sonoros, músicas simples e feedback para botões e sensores. O buzzer passivo precisa de uma frequência gerada pela placa.',
    student: {
      whatIs: 'Uma peça que toca sons e notas.',
      usefulFor: 'Criar alarmes, efeitos e músicas simples.',
      howToConnect: '+ no pino de saída; − no GND.',
      attention: 'Buzzer ativo não toca notas do mesmo jeito.',
      bloquinExample: 'Toque uma nota ao apertar o botão.',
    },
    howItWorks: 'Dentro do buzzer existe um disco fino de cerâmica piezoelétrica colado a um disco metálico. Cada pulso elétrico que chega faz esse disco se curvar um pouquinho; ligando e desligando o pulso muitas vezes por segundo (em uma frequência), o disco vibra para frente e para trás e empurra o ar, criando o som que você ouve. Frequências diferentes tocam notas diferentes.',
    codeLogic: 'Os blocos de tocar som e tocar música pronta escondem uma sequência de frequências (em hertz) e durações. Para cada nota, o Bloquin manda o pino ligar e desligar naquela frequência exata por um tempo determinado, e é essa vibração controlada do disco piezoelétrico que gera o som — trocar a frequência muda a altura da nota (agudo ou grave), e trocar a duração muda quanto tempo ela dura.',
    parts: [
      { label: 'Case plástico', description: 'A caixinha preta que protege as peças internas e direciona o som para fora.' },
      { label: 'Disco piezoelétrico', description: 'O disco metálico escondido dentro, que vibra quando recebe pulsos elétricos.' },
      { label: 'Terminal + (positivo)', description: 'Costuma ter marca ou perna mais longa; liga ao pino de saída.' },
      { label: 'Terminal − (negativo)', description: 'A outra perna; liga ao GND.' },
    ],
    tags: ['som', 'saída', 'tom', 'piezo'],
    specifications: ['Normalmente possui marcação + e −', 'Controlado por frequência', 'Compatível com os blocos de tocar som', 'Consumo baixo em comparação a motores'],
    pins: [
      { label: '+', role: 'signal', description: 'Conecte a um pino digital de saída.' },
      { label: '−', role: 'ground', description: 'Conecte ao GND.' },
    ],
    connections: [
      { title: 'Buzzer básico', description: 'Pino digital → terminal +; terminal − → GND.' },
    ],
    cautions: ['Um buzzer ativo apenas liga/desliga e não toca notas da mesma forma; confirme o tipo.', 'Evite volumes ou frequências incômodas perto do ouvido.'],
    relatedBlocks: [
      { blockType: 'buzzer_tocar', label: 'Tocar som', toolboxCategory: 'Buzzer' },
      { blockType: 'buzzer_tocar_tempo', label: 'Tocar som por tempo', toolboxCategory: 'Buzzer' },
      { blockType: 'buzzer_tocar_musica', label: 'Tocar música pronta', toolboxCategory: 'Buzzer' },
    ],
    relatedComponentIds: ['push-button', 'arduino-uno', 'esp32-devkit-v1'],
    media: [{ kind: 'image', role: 'main', src: buzzerImage, alt: 'Buzzer passivo' }],
  },
  {
    id: 'ldr',
    name: 'LDR',
    categoryId: 'sensors',
    illustration: 'ldr',
    summary: 'Resistor dependente de luz: sua resistência varia conforme a iluminação.',
    purpose: 'Permite que o projeto perceba claro e escuro. Em conjunto com um resistor fixo, produz uma tensão que a placa lê em uma entrada analógica.',
    student: {
      whatIs: 'Um sensor que percebe claro e escuro.',
      usefulFor: 'Fazer o projeto reagir à luz.',
      howToConnect: 'Use LDR e resistor juntos; leia o ponto do meio.',
      attention: 'Ele precisa de um resistor para medir direito.',
      bloquinExample: 'Acenda uma luz quando escurecer.',
    },
    howItWorks: 'O LDR é feito de um material sensível à luz: quanto mais fótons (partículas de luz) batem nele, mais fácil fica para a corrente elétrica atravessá-lo — ou seja, sua resistência cai. No escuro, o material dificulta a passagem de corrente e a resistência sobe bastante. É essa mudança que a placa consegue enxergar através do divisor de tensão.',
    codeLogic: 'O bloco de ler pino analógico não lê o LDR sozinho: ele lê a tensão no meio do divisor formado por LDR + resistor. Quando está claro, o LDR deixa passar mais corrente e o número lido muda em um sentido; no escuro, muda no sentido oposto. Um bloco de se... então compara esse número com um valor de referência para decidir, por exemplo, quando acender uma luz.',
    parts: [
      { label: 'Trilha sensível à luz', description: 'O desenho em zigue-zague na frente do sensor — é a parte que reage à luz.' },
      { label: 'Corpo de resina', description: 'A camada transparente que protege a trilha da poeira e da umidade.' },
      { label: 'Terminais', description: 'Os dois fios metálicos, sem polaridade — podem ser ligados em qualquer ordem no divisor de tensão.' },
    ],
    tags: ['luz', 'analógico', 'fotoresistor', 'divisor de tensão'],
    specifications: ['Não possui polaridade', 'Precisa de resistor fixo para leitura analógica', 'Resposta gradual à luz', 'Leitura depende do ambiente e da montagem'],
    pins: [
      { label: 'Terminal 1', role: 'analog', description: 'Pode ser conectado em qualquer lado do divisor.' },
      { label: 'Terminal 2', role: 'analog', description: 'Pode ser conectado em qualquer lado do divisor.' },
    ],
    connections: [
      { title: 'Divisor de tensão', description: 'VCC → LDR → ponto de leitura analógica → resistor de 10 kΩ → GND.' },
      { title: 'Ajuste de limite', description: 'Leia valores no ambiente claro e escuro para decidir o número usado em uma condição.' },
    ],
    cautions: ['O valor lido não é uma unidade de lux; calibre para o ambiente.', 'No ESP32, mantenha a tensão no pino analógico dentro de 3,3 V.'],
    relatedBlocks: [
      { blockType: 'ler_pino_analogico', label: 'Ler sensor analógico', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'comparar_valores', label: 'Comparar valores', toolboxCategory: 'Lógica' },
      { blockType: 'mapear_valor', label: 'Converter escala', toolboxCategory: 'Matemática' },
    ],
    relatedComponentIds: ['resistor', 'led-5mm', 'arduino-uno'],
    media: [{ kind: 'image', role: 'main', src: ldrImage, alt: 'Sensor LDR' }],
  },
  {
    id: 'hc-sr04',
    name: 'HC-SR04',
    categoryId: 'sensors',
    illustration: 'ultrasonic',
    summary: 'Sensor ultrassônico que mede distância usando pulso de som.',
    purpose: 'Envia um pulso ultrassônico pelo TRIG e mede o retorno no ECHO para estimar a distância de objetos à frente.',
    student: {
      whatIs: 'Um sensor que mede a distância até um objeto.',
      usefulFor: 'Fazer o robô perceber obstáculos.',
      howToConnect: 'VCC e GND; TRIG envia, ECHO recebe.',
      attention: 'No ESP32, proteja o pino ECHO de 5 V.',
      bloquinExample: 'Pare o robô quando algo chegar perto.',
    },
    howItWorks: 'O sensor tem dois "olhos" cilíndricos: um fala (emissor) e o outro escuta (receptor). Quando a placa manda um pulso curto no TRIG, o emissor solta um estouro de som muito agudo — ultrassom, que nossos ouvidos não conseguem escutar — várias vezes seguidas. O som viaja pelo ar, bate em um objeto na frente e volta como eco. O receptor escuta esse eco, e o sensor mantém o pino ECHO em nível alto durante todo o tempo em que o som estava viajando de ida e volta: quanto mais longe o objeto, mais tempo o ECHO fica ligado.',
    codeLogic: 'O bloco de ler distância esconde uma sequência: primeiro coloca o TRIG em nível alto por 10 microssegundos exatos (rápido demais para perceber, mas suficiente para o sensor disparar o som). Depois, ele mede quantos microssegundos o ECHO fica em nível alto e faz uma continha: como o som viaja a uma velocidade conhecida no ar, dividir esse tempo por dois (ida e volta) e multiplicar pela velocidade do som dá a distância em centímetros. O bloco de objeto está perto? só compara esse resultado com um número que você escolhe.',
    parts: [
      { label: 'Emissor (T)', description: 'O cilindro marcado com "T" de Transmitter — solta o som ultrassônico.' },
      { label: 'Receptor (R)', description: 'O cilindro marcado com "R" de Receiver — escuta o eco que volta.' },
      { label: 'Placa de circuito', description: 'A base verde com o chip que controla o tempo dos pulsos e calcula o eco.' },
      { label: 'Pinos VCC, TRIG, ECHO, GND', description: 'As quatro conexões: energia, disparo, retorno e terra, na ordem impressa na placa.' },
    ],
    tags: ['distância', 'ultrassom', 'TRIG', 'ECHO'],
    specifications: ['Alimentação típica: 5 V', 'Faixa típica: cerca de 2 cm a 4 m', 'Usa um pino de disparo e um de eco', 'O ECHO de módulos comuns é nível lógico de 5 V'],
    pins: [
      { label: 'VCC', role: 'power', description: 'Alimentação de 5 V no módulo comum.' },
      { label: 'GND', role: 'ground', description: 'Terra comum.' },
      { label: 'TRIG', role: 'digital', description: 'Entrada de disparo ligada a um pino de saída da placa.' },
      { label: 'ECHO', role: 'digital', description: 'Saída de retorno ligada a um pino de entrada da placa.' },
    ],
    connections: [
      { title: 'Arduino Uno', description: 'VCC em 5V, GND em GND, TRIG em saída digital e ECHO em entrada digital.' },
      { title: 'ESP32', description: 'Alimente conforme o módulo e reduza o sinal ECHO de 5 V para 3,3 V com divisor ou conversor de nível.' },
    ],
    cautions: ['Não conecte o ECHO de 5 V diretamente a um GPIO do ESP32.', 'Superfícies macias, inclinadas ou muito próximas podem gerar leituras instáveis.'],
    relatedBlocks: [
      { blockType: 'configurar_ultrassonico', label: 'Configurar sensor de distância', toolboxCategory: 'Sensor de Distância' },
      { blockType: 'ler_distancia_cm', label: 'Ler distância (cm)', toolboxCategory: 'Sensor de Distância' },
      { blockType: 'objeto_esta_perto', label: 'Objeto está perto?', toolboxCategory: 'Sensor de Distância' },
    ],
    relatedComponentIds: ['arduino-uno', 'esp32-devkit-v1', 'led-5mm'],
    media: [{ kind: 'image', role: 'main', src: hcSr04Image, alt: 'Sensor ultrassônico HC-SR04' }],
  },
  {
    id: 'mpu6050',
    name: 'MPU6050',
    categoryId: 'modules',
    illustration: 'imu',
    summary: 'Módulo com acelerômetro e giroscópio para detectar inclinação e movimento.',
    purpose: 'Mede aceleração e rotação. No Bloquin, os blocos do acelerômetro oferecem valores de inclinação frente/trás e lateral.',
    student: {
      whatIs: 'Um sensor que percebe inclinação e movimento.',
      usefulFor: 'Controlar projetos ao inclinar uma peça.',
      howToConnect: 'Ligue VCC, GND, SDA e SCL.',
      attention: 'Veja na placa se ela usa 3,3 V ou 5 V.',
      bloquinExample: 'Incline para virar o robô.',
    },
    howItWorks: 'Dentro do chip existem estruturas microscópicas que se movem ligeiramente quando o sensor acelera ou gira — parecido com sentir o corpo ser empurrado para o lado em um carro fazendo curva. O acelerômetro mede essa força em três direções (X, Y, Z), e o giroscópio mede a velocidade de rotação nos mesmos três eixos. O chip transforma esses movimentos minúsculos em números elétricos e os envia pela conexão I²C sempre que a placa pergunta.',
    codeLogic: 'O bloco de iniciar MPU6050 conversa com o chip pela primeira vez, no endereço escolhido (0x68 ou 0x69), e confere se ele respondeu. Depois, ler inclinação frente/trás e ler inclinação lateral pedem ao chip os números mais recentes de aceleração em cada eixo e fazem, por trás dos panos, uma continha de trigonometria para transformá-los em um ângulo de inclinação em graus — bem mais fácil de usar em um bloco de se... então do que os valores brutos do sensor. Quando os valores brutos são úteis (por exemplo, para detectar uma batida ou um giro rápido), os blocos de aceleração X/Y/Z e rotação X/Y/Z devolvem exatamente o que o acelerômetro e o giroscópio medem, sem nenhuma conversão.',
    parts: [
      { label: 'Chip MPU6050', description: 'O quadradinho preto no centro da placa — é onde moram o acelerômetro e o giroscópio, juntos no mesmo chip.' },
      { label: 'Pinos SDA e SCL', description: 'As duas linhas de comunicação I²C: uma carrega os dados, a outra marca o ritmo (clock).' },
      { label: 'Pino AD0', description: 'Muda o endereço I²C do módulo (0x68 normalmente, 0x69 se ligado a VCC) — útil com dois sensores no mesmo barramento.' },
      { label: 'Furos de fixação', description: 'Os pequenos furos nos cantos da placa, para parafusá-la firme no robô e evitar leituras tremidas.' },
    ],
    tags: ['I²C', 'acelerômetro', 'giroscópio', 'inclinação'],
    specifications: ['Comunicação I²C', 'Acelerômetro de 3 eixos', 'Giroscópio de 3 eixos', 'Endereço I²C normalmente 0x68'],
    pins: [
      { label: 'VCC', role: 'power', description: 'Verifique a serigrafia do breakout; muitos aceitam 3,3 V ou 5 V na alimentação.' },
      { label: 'GND', role: 'ground', description: 'Terra comum.' },
      { label: 'SDA', role: 'i2c', description: 'Linha de dados I²C; A4 no Uno e GPIO 21 no ESP32 por padrão.' },
      { label: 'SCL', role: 'i2c', description: 'Linha de clock I²C; A5 no Uno e GPIO 22 no ESP32 por padrão.' },
    ],
    connections: [
      { title: 'Arduino Uno', description: 'SDA → A4, SCL → A5, GND comum e alimentação conforme o seu módulo.' },
      { title: 'ESP32', description: 'SDA → GPIO 21 e SCL → GPIO 22 são os padrões recomendados pelo Bloquin.' },
    ],
    cautions: ['Confira a tensão lógica e os pull-ups do seu breakout antes de usar com ESP32.', 'Mantenha o módulo firme: vibrações e montagem inclinada afetam a leitura.'],
    relatedBlocks: [
      { blockType: 'mpu_iniciar', label: 'Iniciar MPU6050', toolboxCategory: 'MPU6050' },
      { blockType: 'mpu_ler_pitch', label: 'Ler inclinação frente/trás', toolboxCategory: 'MPU6050' },
      { blockType: 'mpu_ler_roll', label: 'Ler inclinação lateral', toolboxCategory: 'MPU6050' },
      { blockType: 'mpu_ler_aceleracao_x', label: 'Aceleração X (bruta)', toolboxCategory: 'MPU6050' },
      { blockType: 'mpu_ler_giro_x', label: 'Rotação X (giroscópio)', toolboxCategory: 'MPU6050' },
    ],
    relatedComponentIds: ['esp32-devkit-v1', 'arduino-uno', 'l298n'],
    media: [{ kind: 'image', role: 'main', src: mpu6050Image, alt: 'Módulo MPU6050' }],
  },
  {
    id: 'l298n',
    name: 'Driver L298N',
    categoryId: 'modules',
    illustration: 'driver',
    summary: 'Ponte H dupla que permite controlar sentido e velocidade de até dois motores DC.',
    purpose: 'Recebe sinais de baixa corrente da placa e fornece energia ao motor por uma fonte apropriada. É o intermediário obrigatório entre placa e motor.',
    student: {
      whatIs: 'A peça que dá força para os motores.',
      usefulFor: 'Fazer rodas girarem para frente ou para trás.',
      howToConnect: 'Placa nos pinos IN/EN; motor nos pinos OUT.',
      attention: 'A bateria do motor vai no driver, não na placa.',
      bloquinExample: 'Faça o robô andar para frente.',
    },
    howItWorks: 'Por dentro, o L298N tem duas "pontes H" — um conjunto de quatro chaves eletrônicas para cada motor, organizadas em formato de H. Ligando pares diferentes dessas chaves, a corrente pode atravessar o motor em um sentido ou no outro, fazendo-o girar para frente ou para trás. O pino de habilitação (EN) liga e desliga essas chaves rapidamente (PWM) para controlar a velocidade média, mesmo a corrente sendo sempre "tudo ou nada" em cada instante.',
    codeLogic: 'O bloco de configurar motor DC define quais pinos da placa vão para IN1–IN4 e ENA/ENB. Para girar, mover robô ou girar motor individual escrevem o par certo de HIGH/LOW nos pinos IN daquele motor (por exemplo, IN1=HIGH e IN2=LOW para frente) e mandam um valor de PWM no pino EN correspondente — quanto maior o valor, mais rápido o motor gira. O bloco de parar motores simplesmente coloca os dois pinos IN em LOW ou o EN em 0, cortando o movimento.',
    parts: [
      { label: 'Chip L298N', description: 'O componente preto retangular com aletas de metal — é a ponte H que aguenta a corrente dos motores.' },
      { label: 'Dissipador de calor', description: 'A peça de metal encaixada no chip. Ele esquenta trabalhando, e o dissipador ajuda a esfriar.' },
      { label: 'Bornes de parafuso', description: 'Os conectores verdes onde entram a bateria dos motores e saem os fios para cada motor.' },
      { label: 'Jumper de 5 V', description: 'Um pino removível que, quando presente, gera 5 V para alimentar a placa a partir da bateria dos motores.' },
    ],
    tags: ['ponte H', 'motor', 'PWM', 'driver'],
    specifications: ['Controla dois motores DC', 'Entradas IN1–IN4 definem o sentido', 'ENA e ENB recebem PWM para velocidade', 'Tem queda de tensão relativamente alta em comparação a drivers modernos'],
    pins: [
      { label: 'ENA / ENB', role: 'signal', description: 'Entradas de habilitação/velocidade; use pinos PWM.' },
      { label: 'IN1–IN4', role: 'digital', description: 'Entradas digitais que definem o sentido dos dois motores.' },
      { label: 'OUT1–OUT4', role: 'motor', description: 'Saídas para os terminais dos motores.' },
      { label: 'Vmotor / GND', role: 'power', description: 'Fonte dos motores e terra comum com a placa.' },
    ],
    connections: [
      { title: 'Sinais da placa', description: 'ENA/ENB em pinos PWM; IN1–IN4 em pinos digitais de saída.' },
      { title: 'Energia e motores', description: 'Fonte externa adequada no driver, motores em OUT1–OUT4 e GND da fonte unido ao GND da placa.' },
    ],
    cautions: ['Nunca alimente o motor pelo pino da placa.', 'Desligue a fonte antes de trocar fios do motor.', 'Confira tensão, corrente e jumpers do módulo L298N antes de ligar.'],
    relatedBlocks: [
      { blockType: 'l298n_configurar_simples', label: 'Configurar motor DC', toolboxCategory: 'Motor DC' },
      { blockType: 'l298n_mover_robo', label: 'Mover robô', toolboxCategory: 'Motor DC' },
      { blockType: 'l298n_mover_motor', label: 'Girar motor individual', toolboxCategory: 'Motor DC' },
      { blockType: 'l298n_parar', label: 'Parar motores', toolboxCategory: 'Motor DC' },
    ],
    relatedComponentIds: ['dc-motor', 'esp32-devkit-v1', 'mpu6050'],
    media: [{ kind: 'image', role: 'main', src: ponteHImage, alt: 'Driver de motor L298N, ponte H' }],
  },
  {
    id: 'dc-motor',
    name: 'Motor DC',
    categoryId: 'motors',
    illustration: 'motor',
    summary: 'Motor de corrente contínua que transforma energia elétrica em rotação.',
    purpose: 'Move rodas, hélices e mecanismos simples. Precisa de um driver, como o L298N, pois exige mais corrente que um pino da placa suporta.',
    student: {
      whatIs: 'O motor que faz uma roda girar.',
      usefulFor: 'Mover rodas, hélices e mecanismos.',
      howToConnect: 'Ligue os dois fios em uma saída do L298N.',
      attention: 'Nunca ligue motor direto em um pino.',
      bloquinExample: 'Gire uma roda pelo driver.',
    },
    howItWorks: 'Dentro do motor há um ímã fixo (o estator) e uma bobina de fio que gira no meio (o rotor). Quando a corrente passa pela bobina, ela vira um ímã temporário; os polos desse ímã temporário são empurrados e puxados pelos polos do ímã fixo, fazendo o rotor girar. Uma peça chamada comutador troca a direção da corrente na bobina a cada meia-volta, exatamente no momento certo, para que o empurrão continue sempre no mesmo sentido e o motor não trave.',
    codeLogic: 'O motor em si não entende blocos — quem entende é o driver (L298N). Mas o resultado do código aparece nele: quando mover robô manda mais PWM para um lado, mais corrente média passa pelo motor daquele lado, girando mais rápido; e quando o driver troca IN1/IN2, ele inverte a corrente que chega aos dois terminais do motor, fazendo o comutador interno trocar o sentido do giro.',
    parts: [
      { label: 'Carcaça com ímãs', description: 'A parte externa do motor. Dentro dela ficam os ímãs fixos que não se movem.' },
      { label: 'Rotor (bobina)', description: 'A parte que gira dentro da carcaça, enrolada com fio de cobre.' },
      { label: 'Comutador e escovas', description: 'Pequenos contatos que trocam o sentido da corrente na bobina a cada meia-volta, mantendo o giro.' },
      { label: 'Eixo', description: 'A haste de metal que sai do motor e gira junto com o rotor — é onde se encaixa a roda ou hélice.' },
      { label: 'Dois terminais', description: 'Os fios por onde a corrente entra e sai; trocar a ordem inverte o sentido do giro.' },
    ],
    tags: ['movimento', 'corrente contínua', 'ponte H', 'robótica'],
    specifications: ['Dois terminais', 'Sentido muda ao inverter a polaridade', 'Velocidade pode ser controlada por PWM via driver', 'Tem corrente de partida maior que a corrente em movimento'],
    pins: [
      { label: 'Terminal A', role: 'motor', description: 'Conecte a uma saída do canal do driver.' },
      { label: 'Terminal B', role: 'motor', description: 'Conecte à outra saída do mesmo canal do driver.' },
    ],
    connections: [
      { title: 'Com L298N', description: 'Ligue os dois terminais em OUT1/OUT2 ou OUT3/OUT4. Inverta-os se o sentido desejado ficar oposto.' },
      { title: 'Alimentação', description: 'A fonte do motor entra no driver, não nos GPIOs ou no 5V/3V3 da placa.' },
    ],
    cautions: ['Não conecte um motor diretamente a um GPIO.', 'Motores geram ruído elétrico; mantenha fios firmes e fonte compatível.', 'Verifique a corrente de partida para não sobrecarregar o driver ou a bateria.'],
    relatedBlocks: [
      { blockType: 'l298n_configurar_simples', label: 'Configurar motor DC', toolboxCategory: 'Motor DC' },
      { blockType: 'l298n_mover_robo', label: 'Mover robô', toolboxCategory: 'Motor DC' },
      { blockType: 'l298n_mover_motor', label: 'Girar motor individual', toolboxCategory: 'Motor DC' },
    ],
    relatedComponentIds: ['l298n', 'esp32-devkit-v1', 'arduino-uno'],
    media: [{ kind: 'image', role: 'main', src: motorImage, alt: 'Motor de corrente contínua' }],
  },
  {
    id: 'lcd-i2c-16x2',
    name: 'Display LCD I²C 16x2',
    categoryId: 'modules',
    illustration: 'display',
    summary: 'Tela de caracteres com um módulo I²C soldado atrás, para mostrar texto e números com só dois fios de dados.',
    purpose: 'Mostra até 32 caracteres (16 colunas × 2 linhas) sem precisar do monitor serial — útil para projetos que rodam longe do computador, como uma estação de sensores ou um contador visível de longe.',
    student: {
      whatIs: 'Uma telinha para mostrar texto e números.',
      usefulFor: 'Exibir uma leitura de sensor, uma mensagem ou um contador sem precisar do computador.',
      howToConnect: 'Ligue VCC, GND, SDA e SCL — os mesmos dois fios de dados de qualquer sensor I²C.',
      attention: 'Se aparecerem só quadrados ou nada na tela, gire o potenciômetro azul atrás do módulo (ajusta o contraste).',
      bloquinExample: 'Mostre a distância medida pelo sensor ultrassônico direto na tela.',
    },
    howItWorks: 'O vidro do display tem uma grade de 5×8 pontos para cada uma das 32 posições de caractere — um chip controlador (o HD44780, ou compatível) já vem soldado no próprio LCD e sabe desenhar letras e números nessa grade a partir de comandos. Só que esse chip normalmente precisa de mais de dez fios para receber comando; o módulo azul/verde colado atrás resolve isso: é um pequeno expansor de portas (PCF8574) que conversa por I²C (só dois fios, SDA e SCL) e traduz cada byte recebido em pulsos elétricos para o controlador do LCD, incluindo um pino extra que liga a luz de fundo.',
    codeLogic: 'O bloco de iniciar manda, pelo I²C, a sequência de comandos que o controlador do display espera logo ao ligar (é sempre a mesma, documentada no datasheet do HD44780) e termina apagando a tela. Escrever texto ou valor manda cada caractere, um de cada vez, para a posição atual do "cursor" — uma coordenada interna (coluna, linha) que avança sozinha a cada caractere escrito. O bloco de posicionar cursor muda essa coordenada antes de escrever, e limpar tela zera tudo e volta o cursor para coluna 0, linha 0.',
    parts: [
      { label: 'Painel de cristal líquido', description: 'A parte cinza/verde com os caracteres. Cada posição é uma grade de pontinhos que se apagam ou acendem para formar uma letra.' },
      { label: 'Módulo expansor I²C', description: 'A placa pequena soldada atrás do LCD — nela ficam o chip PCF8574, o potenciômetro de contraste e os 4 pinos (VCC, GND, SDA, SCL).' },
      { label: 'Potenciômetro de contraste', description: 'O parafuso azul no módulo expansor. Gire com uma chave de fenda pequena até as letras ficarem visíveis.' },
      { label: 'Jumper da luz de fundo', description: 'Um pino removível que liga/desliga a luz de fundo do display; a maioria dos módulos vem com ele já conectado.' },
    ],
    tags: ['I²C', 'display', 'HD44780', 'PCF8574'],
    specifications: ['Comunicação I²C (2 fios de dados)', '16 colunas × 2 linhas (existem também versões 20×4)', 'Endereço I²C mais comum: 0x27 (às vezes 0x3F)', 'Alimentação normalmente 5 V'],
    pins: [
      { label: 'VCC', role: 'power', description: 'Alimentação do módulo — confira se é 5 V ou 3,3 V na serigrafia da placa.' },
      { label: 'GND', role: 'ground', description: 'Terra comum com a placa.' },
      { label: 'SDA', role: 'i2c', description: 'Linha de dados I²C; A4 no Uno e GPIO 21 no ESP32 por padrão.' },
      { label: 'SCL', role: 'i2c', description: 'Linha de clock I²C; A5 no Uno e GPIO 22 no ESP32 por padrão.' },
    ],
    connections: [
      { title: 'Arduino Uno', description: 'SDA → A4, SCL → A5, GND comum e VCC em 5V.' },
      { title: 'ESP32', description: 'SDA → GPIO 21 e SCL → GPIO 22 são os padrões recomendados pelo Bloquin.' },
      { title: 'Junto com o MPU6050', description: 'I²C é um barramento único: se o projeto também usar o MPU6050, os dois dispositivos compartilham os MESMOS pinos SDA/SCL.' },
    ],
    cautions: ['Sem imagem de conexão nesta versão do Bloquin.', 'Se o texto não aparecer, confira o endereço I²C (0x27 ou 0x3F) antes de suspeitar de fiação.', 'Gire o potenciômetro de contraste antes de concluir que o display não funciona.'],
    relatedBlocks: [
      { blockType: 'lcd_iniciar', label: 'Iniciar Display LCD', toolboxCategory: 'Display LCD' },
      { blockType: 'lcd_posicionar_cursor', label: 'Posicionar cursor', toolboxCategory: 'Display LCD' },
      { blockType: 'lcd_escrever_valor', label: 'Display LCD escreve (valor)', toolboxCategory: 'Display LCD' },
    ],
    relatedComponentIds: ['mpu6050', 'esp32-devkit-v1', 'arduino-uno'],
    media: [],
  },
  {
    id: 'dht11-dht22',
    name: 'Sensor DHT11 / DHT22',
    categoryId: 'sensors',
    illustration: 'dht',
    summary: 'Módulo que mede temperatura e umidade do ar com um único fio de dados.',
    purpose: 'Lê a temperatura e a umidade do ambiente numa única leitura. O DHT22 é mais preciso e tem faixa maior; o DHT11 é mais barato e comum em kits iniciantes.',
    student: {
      whatIs: 'Um sensor que mede calor e umidade do ar.',
      usefulFor: 'Montar uma estação meteorológica simples ou avisar quando o ambiente está muito quente/úmido.',
      howToConnect: 'Ligue VCC, GND e o pino de dados a uma saída da placa.',
      attention: 'Não leia rápido demais: o sensor precisa de pelo menos 1 segundo entre leituras.',
      bloquinExample: 'Mostre a temperatura e a umidade juntas no monitor serial.',
    },
    howItWorks: 'Dentro do módulo existem dois sensores separados: um resistor cuja resistência muda com a umidade do ar, e um termistor cuja resistência muda com a temperatura. Um pequeno chip dentro do próprio módulo já lê os dois e converte para números prontos — diferente do LDR, o Bloquin não precisa calcular nada a partir de um valor analógico bruto, o sensor já entrega o resultado.',
    codeLogic: 'Como o sensor só tem um fio de dados (além de VCC/GND), a placa e o sensor "conversam" no mesmo fio, um de cada vez: a placa manda um pulso curto pedindo uma leitura, e o sensor responde enviando 40 bits (temperatura, umidade e um total de conferência) variando o tempo que o fio fica em nível alto para cada bit — mais tempo em alto significa "1", menos tempo significa "0". O bloco de configurar guarda o pino e o modelo (DHT11 ou DHT22, porque os dois decodificam esses 40 bits de um jeito ligeiramente diferente); os blocos de leitura repetem essa "conversa" no fio sempre que passa tempo suficiente desde a última vez (o sensor é lento, então o valor fica em cache por 2 segundos entre leituras de verdade).',
    parts: [
      { label: 'Case plástico branco ou azul', description: 'A caixinha que protege os dois sensores internos da poeira e umidade excessiva.' },
      { label: 'Grade ventilada', description: 'As aberturas na frente do case, por onde o ar chega até os sensores de umidade e temperatura.' },
      { label: 'Pinos VCC, DATA, GND', description: 'Em módulos de 3 pinos já vêm com resistor de pull-up embutido na placa; sensores "nus" de 4 pinos (sem a placa) precisam de um resistor de 10 kΩ externo entre DATA e VCC.' },
    ],
    tags: ['temperatura', 'umidade', '1 fio', 'DHT11', 'DHT22'],
    specifications: ['DHT11: 0–50 °C, 20–90% UR, leitura a cada ~1 s', 'DHT22: -40–80 °C, 0–100% UR, leitura a cada ~2 s', 'Comunicação digital de 1 fio (protocolo próprio, não é I²C nem SPI)', 'Alimentação 3,3 V–5,5 V'],
    pins: [
      { label: 'VCC', role: 'power', description: 'Alimentação — confira a faixa de tensão aceita pelo módulo.' },
      { label: 'DATA', role: 'digital', description: 'Único fio de dados; ligue a um pino de saída da placa.' },
      { label: 'GND', role: 'ground', description: 'Terra comum com a placa.' },
    ],
    connections: [
      { title: 'Arduino Uno', description: 'DATA em qualquer pino digital, VCC em 5V, GND em GND.' },
      { title: 'ESP32', description: 'DATA em qualquer GPIO de saída; confira se o módulo aceita 3,3 V (a maioria aceita).' },
    ],
    cautions: ['Sem imagem de conexão nesta versão do Bloquin.', 'Leituras muito seguidas (menos de 1 segundo de intervalo) podem falhar — o Bloquin já espera 2 segundos entre leituras de verdade por conta disso.', 'Confira o modelo (DHT11 ou DHT22) impresso no case antes de configurar o bloco.'],
    relatedBlocks: [
      { blockType: 'dht_iniciar', label: 'Configurar Sensor DHT11/DHT22', toolboxCategory: 'Sensor de Temperatura e Umidade' },
      { blockType: 'dht_ler_temperatura', label: 'Temperatura do DHT', toolboxCategory: 'Sensor de Temperatura e Umidade' },
      { blockType: 'dht_ler_umidade', label: 'Umidade do DHT', toolboxCategory: 'Sensor de Temperatura e Umidade' },
    ],
    relatedComponentIds: ['esp32-devkit-v1', 'arduino-uno', 'hc-sr04'],
    media: [],
  },
  {
    id: 'neopixel-strip',
    name: 'Tira de LEDs Endereçáveis (NeoPixel/WS2812)',
    categoryId: 'actuators',
    illustration: 'led-strip',
    summary: 'Fita ou anel de LEDs em que cada um pode receber uma cor diferente, controlados por um único fio de dados.',
    purpose: 'Cria efeitos de luz e cor programáveis — cada LED da tira recebe sua própria cor (vermelho, verde e azul), formando padrões, animações ou indicadores visuais.',
    student: {
      whatIs: 'Uma fita de luzes coloridas que você programa LED por LED.',
      usefulFor: 'Fazer efeitos de luz, indicadores coloridos ou decoração programável.',
      howToConnect: 'Ligue VCC, GND e o fio de dados (DIN) a um pino de saída.',
      attention: 'Sempre chame "Atualizar Tira de LEDs" depois de definir as cores, ou nada aparece.',
      bloquinExample: 'Acenda o primeiro LED de uma cor diferente para cada botão do controle remoto.',
    },
    howItWorks: 'Cada LED da tira é, na verdade, um LED colorido (vermelho+verde+azul) com um pequeno chip controlador embutido, ligado em série com os vizinhos. Os dados chegam por um único fio: a placa manda uma sequência de pulsos elétricos representando a cor de cada LED, um atrás do outro; o primeiro chip da fila lê os dados da sua própria cor, deixa o resto passar para o próximo LED, e assim por diante — por isso não existe "ligar só um LED": a tira inteira recebe a sequência de novo a cada atualização.',
    codeLogic: 'Definir cor do LED só guarda a cor escolhida (vermelho, verde, azul, de 0 a 255 cada) numa lista na memória da placa — a tira física ainda não muda. Só quando Atualizar Tira de LEDs roda é que a placa manda toda essa lista, LED por LED, pelo fio de dados, no protocolo exato que o chip de cada LED entende. Separar "definir" de "mostrar" evita mandar a tira inteira de novo a cada LED que muda — você desenha o quadro inteiro primeiro, depois manda de uma vez.',
    parts: [
      { label: 'LEDs individuais (WS2812/WS2812B)', description: 'Cada quadradinho da fita é um LED RGB com o chip controlador já embutido dentro dele mesmo.' },
      { label: 'Fio de dados (DIN)', description: 'A entrada por onde a sequência de cores chega — geralmente marcada com uma seta apontando a direção do sinal.' },
      { label: 'Fios de alimentação (5V/GND)', description: 'Alimentam todos os LEDs da tira; tiras longas ou muito brilhantes pedem uma fonte externa.' },
    ],
    tags: ['RGB', 'endereçável', 'WS2812', '1 fio'],
    specifications: ['Protocolo de 1 fio, timing muito preciso (a Bloquin usa a biblioteca Adafruit_NeoPixel para isso)', 'Cada LED: 3 canais de 0–255 (vermelho, verde, azul)', 'Alimentação normalmente 5 V', 'Consumo alto no branco/brilho máximo — até ~60 mA por LED'],
    pins: [
      { label: '5V (ou VCC)', role: 'power', description: 'Alimentação da tira — em tiras longas, prefira uma fonte externa em vez do 5V da placa.' },
      { label: 'GND', role: 'ground', description: 'Terra comum com a placa — obrigatório mesmo usando fonte externa para a tira.' },
      { label: 'DIN (Data In)', role: 'digital', description: 'Entrada de dados; ligue a um pino de saída digital da placa.' },
    ],
    connections: [
      { title: 'Arduino Uno/ESP32', description: 'DIN em qualquer pino de saída, GND comum com a placa, 5V direto na tira (fonte externa para tiras longas).' },
      { title: 'ESP32 (cuidado extra)', description: 'A lógica do ESP32 é de 3,3 V; tiras de 5 V podem precisar de um conversor de nível no fio DIN para funcionar de forma confiável.' },
    ],
    cautions: ['Sem imagem de conexão nesta versão do Bloquin.', 'Nunca alimente uma tira grande pelo pino 5V/3V3 da placa — use fonte externa e uma referência de GND comum.', 'Sempre chame "Atualizar Tira de LEDs" depois de "Definir Cor" — as cores só ficam na memória até essa chamada.'],
    relatedBlocks: [
      { blockType: 'neopixel_iniciar', label: 'Configurar Tira de LEDs', toolboxCategory: 'LED Endereçável' },
      { blockType: 'neopixel_definir_cor', label: 'Definir cor do LED', toolboxCategory: 'LED Endereçável' },
      { blockType: 'neopixel_mostrar', label: 'Atualizar Tira de LEDs', toolboxCategory: 'LED Endereçável' },
    ],
    relatedComponentIds: ['esp32-devkit-v1', 'arduino-uno', 'led-5mm'],
    media: [],
  },
  {
    id: 'ir-receiver',
    name: 'Receptor Infravermelho',
    categoryId: 'modules',
    illustration: 'ir',
    summary: 'Módulo pequeno e escuro que capta os pulsos de luz infravermelha de um controle remoto.',
    purpose: 'Permite controlar o projeto à distância com um controle remoto simples, os mesmos que acompanham a maioria dos kits iniciantes de Arduino.',
    student: {
      whatIs: 'Um sensor que "enxerga" o controle remoto.',
      usefulFor: 'Controlar o projeto apertando botões de um controle remoto, sem fio nem Bluetooth.',
      howToConnect: 'Ligue VCC, GND e o pino de sinal a uma entrada da placa.',
      attention: 'Aponte o controle direto para o sensor; luz solar forte pode atrapalhar a leitura.',
      bloquinExample: 'Aperte um botão do controle para trocar a cor de um LED.',
    },
    howItWorks: 'O controle remoto pisca um LED infravermelho (invisível para o olho humano) muitas vezes por segundo, ligando e desligando rapidinho num ritmo específico para cada bit de informação — é como um código Morse de luz. O receptor tem um sensor que só reage a essa faixa de luz infravermelha e devolve um sinal elétrico que "acompanha" esse piscar: nível baixo quando o LED do controle está aceso, nível alto quando está apagado.',
    codeLogic: 'O bloco de configurar só guarda o pino do sensor. "Chegou um Código do Controle Remoto?" é quem faz o trabalho de verdade: fica de olho no pino esperando o começo de uma transmissão (uma marca bem mais longa que as outras) e, se encontrar, mede a duração de cada um dos 32 pulsos seguintes para decidir se cada um representa um "0" ou um "1" — pulsos mais curtos viram 0, mais longos viram 1. Esses 32 bits formam um número que identifica o botão apertado, devolvido por "Código Recebido do Controle Remoto". Como essa leitura não usa interrupção, é possível perder um aperto de botão se o programa estiver ocupado bem naquele instante — nesse caso, é só apertar de novo.',
    parts: [
      { label: 'Case preto', description: 'A cúpula escura na frente do módulo — deixa passar só a luz infravermelha, filtrando luz visível que atrapalharia a leitura.' },
      { label: 'Sensor fotodiodo', description: 'Escondido dentro do case preto — é a peça que realmente reage à luz infravermelha do controle.' },
      { label: 'Três pernas (VCC, GND, sinal)', description: 'A ordem varia entre módulos — confira a serigrafia da placa antes de ligar.' },
    ],
    tags: ['infravermelho', 'controle remoto', 'NEC', '1 fio'],
    specifications: ['Decodifica o protocolo NEC (o mais comum em controles pequenos de kit)', 'Alcance típico de alguns metros em linha reta', 'Alimentação normalmente 3,3–5 V', 'Leitura por consulta (sem interrupção) — pode perder um código ocasional'],
    pins: [
      { label: 'VCC', role: 'power', description: 'Alimentação — confira a tensão aceita pelo módulo.' },
      { label: 'GND', role: 'ground', description: 'Terra comum com a placa.' },
      { label: 'OUT (sinal)', role: 'digital', description: 'Sinal de saída; ligue a qualquer pino de entrada da placa, inclusive os pinos só-entrada do ESP32.' },
    ],
    connections: [
      { title: 'Arduino Uno/ESP32', description: 'OUT em qualquer pino digital, VCC e GND conforme a tensão do módulo.' },
    ],
    cautions: ['Sem imagem de conexão nesta versão do Bloquin.', 'Luz solar direta ou lâmpadas fluorescentes fortes podem atrapalhar a leitura.', 'Funciona só com controles que usam o protocolo NEC — a maioria dos controles pequenos de kit, mas não todos.'],
    relatedBlocks: [
      { blockType: 'ir_iniciar', label: 'Configurar Receptor Infravermelho', toolboxCategory: 'Receptor Infravermelho' },
      { blockType: 'ir_disponivel', label: 'Chegou um código do controle remoto?', toolboxCategory: 'Receptor Infravermelho' },
      { blockType: 'ir_ler_codigo', label: 'Código recebido do controle remoto', toolboxCategory: 'Receptor Infravermelho' },
    ],
    relatedComponentIds: ['esp32-devkit-v1', 'arduino-uno', 'neopixel-strip'],
    media: [],
  },
  {
    id: 'potentiometer',
    name: 'Potenciômetro',
    categoryId: 'sensors',
    illustration: 'potentiometer',
    summary: 'Um "botão giratório" que muda de resistência conforme você gira — uma entrada analógica controlada à mão.',
    purpose: 'Permite que a pessoa ajuste um valor manualmente — volume, velocidade, ângulo — em vez de o projeto reagir sozinho a um sensor ambiental.',
    student: {
      whatIs: 'Um botão que você gira para mudar um valor.',
      usefulFor: 'Ajustar velocidade, brilho, volume ou qualquer valor à mão.',
      howToConnect: 'Ligue os dois lados externos em alimentação/GND e o pino do meio numa entrada analógica.',
      attention: 'Sozinho ele não faz nada — só muda um número que a placa lê.',
      bloquinExample: 'Gire o potenciômetro para escolher a força de um motor.',
    },
    howItWorks: 'Por dentro existe uma trilha resistiva (parecida com a de um resistor) e um cursor metálico que desliza sobre ela quando o eixo gira. Os dois terminais das pontas ficam ligados às extremidades da trilha; o terminal do meio está ligado a esse cursor. Girar o eixo move o cursor pela trilha, mudando a proporção de resistência de cada lado — é exatamente o mesmo princípio do divisor de tensão usado com o LDR, só que a "variável" agora é a posição de um eixo em vez da luz do ambiente.',
    codeLogic: 'O bloco de ler sensor analógico lê a tensão no pino do meio, que varia de acordo com a posição do cursor: girado para um lado, o número fica perto de 0; girado para o outro, perto do máximo da placa (1023 no Uno/Nano, 4095 no ESP32). É a mesma leitura usada para o LDR — o potenciômetro não precisa de nenhum bloco próprio, "Converter Escala" e "Comparar Valores" já resolvem qualquer projeto com ele.',
    parts: [
      { label: 'Corpo com trilha resistiva', description: 'A base onde mora a trilha de material resistivo em formato de arco.' },
      { label: 'Eixo giratório', description: 'A parte que você gira com os dedos ou uma chave de fenda, conectada ao cursor interno.' },
      { label: 'Três terminais', description: 'Dois nas pontas da trilha (alimentação e GND) e um no cursor (o que vai para a entrada analógica).' },
    ],
    tags: ['analógico', 'divisor de tensão', 'entrada manual', '10 kΩ'],
    specifications: ['Não precisa de bloco próprio — usa "Ler Sensor Analógico" como qualquer entrada analógica', 'Valores comuns: 1 kΩ a 100 kΩ (10 kΩ é um valor típico para uso com a placa)', 'Três terminais, sem parte "certa" entre os dois das pontas'],
    pins: [
      { label: 'Terminal 1 (ponta)', role: 'power', description: 'Ligue à alimentação (5V ou 3,3V) ou ao GND — a ordem entre os dois das pontas só inverte o sentido do giro.' },
      { label: 'Terminal 2 (cursor, meio)', role: 'analog', description: 'Vai para uma entrada analógica da placa.' },
      { label: 'Terminal 3 (ponta)', role: 'ground', description: 'O outro lado da trilha — ligue ao GND se o terminal 1 foi para a alimentação.' },
    ],
    connections: [
      { title: 'Arduino Uno/ESP32', description: 'Pontas em alimentação e GND, terminal do meio numa entrada analógica.' },
    ],
    cautions: ['Sem imagem de conexão nesta versão do Bloquin.', 'Girar até o fim de cada lado é normal — não force além do limite mecânico.'],
    relatedBlocks: [
      { blockType: 'ler_pino_analogico', label: 'Ler sensor analógico', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'mapear_valor', label: 'Converter escala', toolboxCategory: 'Matemática' },
    ],
    relatedComponentIds: ['ldr', 'resistor', 'arduino-uno'],
    media: [],
  },
  {
    id: 'pir-motion-sensor',
    name: 'Sensor PIR de Presença',
    categoryId: 'sensors',
    illustration: 'pir',
    summary: 'Sensor com uma cúpula branca que detecta movimento de pessoas e animais pelo calor do corpo.',
    purpose: 'Percebe quando algo se move na frente dele, sem precisar de câmera — a base clássica de alarmes e luzes automáticas.',
    student: {
      whatIs: 'Um sensor que percebe quando alguém se move perto dele.',
      usefulFor: 'Alarmes, luzes automáticas e projetos que reagem à presença de alguém.',
      howToConnect: 'Ligue VCC, GND e a saída digital a um pino de entrada.',
      attention: 'Demora alguns segundos para "calibrar" assim que é ligado.',
      bloquinExample: 'Acenda um LED quando alguém passar na frente do sensor.',
    },
    howItWorks: 'Todo corpo quente (pessoas, animais) emite luz infravermelha invisível o tempo todo — é calor se espalhando. A cúpula branca na frente do sensor (uma lente especial, chamada lente de Fresnel) concentra essa luz infravermelha em duas metades de um sensor interno. Enquanto nada se move, as duas metades recebem uma quantidade parecida de infravermelho; quando algo quente se move na frente, uma metade recebe mais que a outra por um instante, e é essa diferença que o sensor detecta como "movimento".',
    codeLogic: 'O sensor já entrega um resultado pronto: pino em nível alto quando detecta movimento, nível baixo quando não detecta — exatamente como "Ler Pino Digital" já lê qualquer entrada digital. Não existe bloco próprio porque não há nada para calcular: a decisão "tem movimento ou não" já vem pronta do módulo.',
    parts: [
      { label: 'Lente de Fresnel (cúpula branca)', description: 'A parte branca e translúcida — concentra o infravermelho do ambiente no sensor escondido embaixo dela.' },
      { label: 'Sensor piroelétrico', description: 'Embaixo da lente, é o componente que realmente detecta a variação de infravermelho.' },
      { label: 'Potenciômetros de ajuste', description: 'Alguns módulos têm dois parafusos para ajustar sensibilidade e tempo que o sinal fica ativo — opcional para o primeiro projeto.' },
    ],
    tags: ['movimento', 'presença', 'infravermelho passivo', 'digital'],
    specifications: ['Não precisa de bloco próprio — usa "Ler Pino Digital" como qualquer entrada digital', 'Alimentação normalmente 5 V (alguns módulos aceitam 3,3–5 V)', 'Leva alguns segundos para estabilizar depois de ligado'],
    pins: [
      { label: 'VCC', role: 'power', description: 'Alimentação — confira a tensão aceita pelo módulo.' },
      { label: 'GND', role: 'ground', description: 'Terra comum com a placa.' },
      { label: 'OUT', role: 'digital', description: 'Nível alto quando detecta movimento, baixo quando não — ligue a qualquer pino de entrada.' },
    ],
    connections: [
      { title: 'Arduino Uno/ESP32', description: 'OUT em qualquer pino digital, VCC e GND conforme a tensão do módulo.' },
    ],
    cautions: ['Sem imagem de conexão nesta versão do Bloquin.', 'Espere alguns segundos após ligar antes de testar — o sensor precisa estabilizar.', 'Fontes de calor em movimento (ventilador, sol batendo) também podem disparar o sensor.'],
    relatedBlocks: [
      { blockType: 'ler_pino_digital', label: 'Ler pino digital', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'mudou_para_verdadeiro', label: 'Mudou de falso para verdadeiro?', toolboxCategory: 'Lógica' },
    ],
    relatedComponentIds: ['push-button', 'arduino-uno', 'esp32-devkit-v1'],
    media: [],
  },
  {
    id: 'relay-module',
    name: 'Módulo Relé',
    categoryId: 'actuators',
    illustration: 'relay',
    summary: 'Uma "chave elétrica" controlada pela placa, capaz de ligar/desligar aparelhos de tensão bem maior que 5V.',
    purpose: 'Liga e desliga cargas que a placa nunca poderia acionar diretamente — uma lâmpada, um ventilador, qualquer aparelho de tomada — mantendo os dois circuitos (o da placa e o do aparelho) eletricamente separados.',
    student: {
      whatIs: 'Uma chave que a placa liga e desliga à distância.',
      usefulFor: 'Ligar aparelhos "de verdade" (lâmpada, ventilador) a partir de um pino da placa.',
      howToConnect: 'Ligue VCC, GND e o pino de controle a uma saída digital.',
      attention: 'A fiação de alta tensão do outro lado do relé é perigosa — só um adulto deve mexer nela.',
      bloquinExample: 'Ligue uma lâmpada de tomada quando o sensor de presença detectar alguém.',
    },
    howItWorks: 'Dentro do módulo existe uma bobina de fio enrolada em torno de um pedaço de metal. Quando a placa manda corrente pela bobina (através de um pequeno transistor no próprio módulo, para não sobrecarregar o pino), essa bobina vira um ímã temporário e puxa uma lâminazinha metálica, fechando (ou abrindo) um contato elétrico separado — como um interruptor de luz sendo apertado por um ímã, sem nenhuma ligação elétrica direta entre o lado da placa e o lado do aparelho.',
    codeLogic: 'Para o Bloquin, o pino de controle do relé é uma saída digital comum: "Ligar/Desligar Pino" em HIGH aciona a bobina e fecha o contato (a maioria dos módulos considera LOW como "ligado" — confira a serigrafia "NO"/"NC" do seu módulo específico); LOW desliga. Não existe bloco próprio porque não há nada além de "ligar" e "desligar" um pino — o mesmo bloco que já acende um LED serve para o relé.',
    parts: [
      { label: 'Bobina/relé eletromecânico', description: 'A caixinha azul ou preta no módulo — é onde a bobina e a lâmina de contato ficam.' },
      { label: 'Bornes de parafuso (COM/NO/NC)', description: 'Onde entra a fiação de alta tensão do aparelho: COM (comum), NA/NO (normalmente aberto) e NF/NC (normalmente fechado).' },
      { label: 'LED indicador', description: 'Acende quando o relé está ativado — útil para conferir se o bloco está funcionando sem precisar ligar o aparelho de verdade.' },
    ],
    tags: ['alta tensão', 'chave', 'digital', 'isolamento elétrico'],
    specifications: ['Não precisa de bloco próprio — usa "Ligar/Desligar Pino" como qualquer saída digital', 'Sinal de controle: 3,3–5 V (baixa tensão, lado da placa)', 'Contatos: suportam tensão de rede elétrica (127/220 V) e correntes de alguns amperes, conforme o módulo'],
    pins: [
      { label: 'VCC', role: 'power', description: 'Alimentação do módulo (lado de baixa tensão) — confira 3,3 V ou 5 V.' },
      { label: 'GND', role: 'ground', description: 'Terra comum com a placa (lado de baixa tensão).' },
      { label: 'IN (sinal)', role: 'digital', description: 'Pino de controle — ligue a qualquer pino de saída digital da placa.' },
      { label: 'COM / NO / NC', role: 'signal', description: 'Lado de alta tensão, isolado da placa — é aqui que o aparelho controlado se conecta.' },
    ],
    connections: [
      { title: 'Lado da placa', description: 'VCC, GND e IN como qualquer módulo digital comum.' },
      { title: 'Lado do aparelho (alta tensão)', description: 'Fiação separada da placa, feita por um adulto — nunca compartilhe o GND da placa com o lado de alta tensão.' },
    ],
    cautions: ['Sem imagem de conexão nesta versão do Bloquin.', 'O lado de alta tensão (COM/NO/NC) pode ter a tensão da rede elétrica — perigo real de choque; só um adulto deve montar essa parte.', 'Nunca alimente o próprio relé (VCC/GND) pela fiação de alta tensão — são circuitos separados de propósito.'],
    relatedBlocks: [
      { blockType: 'escrever_pino', label: 'Ligar/desligar pino', toolboxCategory: 'Entradas e Saídas' },
      { blockType: 'configurar_pino', label: 'Configurar pino como saída', toolboxCategory: 'Entradas e Saídas' },
    ],
    relatedComponentIds: ['esp32-devkit-v1', 'arduino-uno', 'l298n'],
    media: [],
  },
];

export const COMPONENT_BY_ID: ReadonlyMap<ComponentId, ComponentCatalogItem> = new Map(
  COMPONENT_CATALOG.map((component): [ComponentId, ComponentCatalogItem] => [component.id, component]),
);

export function getComponentById(id: ComponentId | null | undefined): ComponentCatalogItem | undefined {
  return id ? COMPONENT_BY_ID.get(id) : undefined;
}

export function getComponentsByCategory(categoryId: ComponentCategoryId): readonly ComponentCatalogItem[] {
  return COMPONENT_CATALOG.filter((component) => component.categoryId === categoryId);
}

export function isComponentId(value: string): value is ComponentId {
  return COMPONENT_BY_ID.has(value as ComponentId);
}
