-- Marcador histórico: esta versão consta como aplicada no projeto remoto.
-- O SQL original foi preservado em ../migration-history/original/20260727151415_optimize_app_rls_auth_checks.sql.
-- O estado consolidado de public/private é restaurado pela migration
-- 20260727144628_add_audit_query_indexes.sql.
